---
version: "3.8"
services:
  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file: .env-postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    networks:
      - back
    volumes:
      - postgres-data:/var/lib/postgresql/data

  front:
    image: ghcr.io/thetranscendenceteam/front:latest
    restart: on-failure
    env_file: .env-front
    ports:
      - 80:8080
    networks:
      - front
    volumes:
            - front-data:/data # Needed ?

  back:
    image: ghcr.io/thetranscendenceteam/back:latest
    restart: on-failure
    env_file: .env-back
    networks:
      - back
      - front
    volumes:
            - back-data:/data # Needed ?

volumes:
  postgres-data:
  front-data:
  back-data:

networks:
  front:
  back:
