---
version: "3.8"
services:
  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file: .env-postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    networks:
      - back
    volumes:
      - postgres-data:/var/lib/postgresql/data

  front:
    image: ghcr.io/thetranscendenceteam/front:latest
    build:
      context: ..
      dockerfile: images/front/Dockerfile
    restart: on-failure
    env_file: .env-front
    environment:
      - NODE_ENV=production
    ports:
      - 80:8080
    networks:
      - front
    volumes:
      - ../src/front:/app
      - front-data:/data # Needed ?

  back:
    image: ghcr.io/thetranscendenceteam/back:latest
    build:
      context: ..
      dockerfile: images/back/Dockerfile
    restart: on-failure
    env_file: .env-back
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - back
      - front
    volumes:
      - ../src/back:/app
      - back-data:/data # Needed ?

volumes:
  postgres-data:
  front-data:
  back-data:

networks:
  front:
  back:
