---
version: "3.8"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - db
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    #ports:
    #  - 6379:6379

  postgres:
    image: postgres:15.4-alpine
    restart: unless-stopped
    env_file: .env-postgres
    healthcheck:
      test: pg_isready || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  front:
    image: ghcr.io/thetranscendenceteam/front:latest
    build:
      context: ..
      dockerfile: images/front/Dockerfile
    restart: unless-stopped
    #env_file: .env-front
    healthcheck:
      test: curl -f -s http://127.0.0.1:3000/ > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    depends_on:
      back:
        condition: service_healthy
    networks:
      - back
    volumes:
      - front-data:/data # Neede ?
      - .env-front:/app/.env.local

  back:
    image: ghcr.io/thetranscendenceteam/back:latest
    build:
      context: ..
      dockerfile: images/back/Dockerfile
    restart: unless-stopped
    #env_file: .env-back
    healthcheck:
      test: curl -f -s http://127.0.0.1:3000/health > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - db
      - back
    volumes:
      - back-data:/data # Needed ?
      - .env-back:/app/.env

  nginx:
    image: ghcr.io/thetranscendenceteam/nginx:latest
    build:
      context: ..
      dockerfile: images/nginx/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - back
      - front
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - back
    volumes:
      - nginx-ssl:/etc/nginx/ssl

volumes:
  postgres-data:
  front-data:
  back-data:
  nginx-ssl:

networks:
  back:
  db:
