---
version: "3.8"
services:
  redis:
    image: redis:alpine
    networks:
      - back
    #ports:
    #  - 6379:6379

  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file: .env-postgres
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  front:
    image: ghcr.io/thetranscendenceteam/front:latest
    build:
      context: ..
      dockerfile: images/front/Dockerfile
    restart: on-failure
    #env_file: .env-front
    networks:
      - back
    volumes:
      - front-data:/data # Neede ?
      - .env-front:/app/.env.local

  back:
    image: ghcr.io/thetranscendenceteam/back:latest
    build:
      context: ..
      dockerfile: images/back/Dockerfile
    restart: on-failure
    #env_file: .env-back
    depends_on:
      - postgres
    networks:
      - back
      - db
    volumes:
      - back-data:/data # Needed ?
      - .env-back:/app/.env

  nginx:
    image: ghcr.io/thetranscendenceteam/nginx:latest
    build:
      context: ..
      dockerfile: images/nginx/Dockerfile
    restart: on-failure
    depends_on:
      - back
      - front
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - back
    volumes:
      - nginx-ssl:/etc/nginx/ssl

volumes:
  postgres-data:
  front-data:
  back-data:
  nginx-ssl:

networks:
  back:
  db:
