---
version: "3.8"
services:
  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file: .env-postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  front:
    image: ghcr.io/thetranscendenceteam/front:latest
    build:
      context: ..
      dockerfile: images/front/Dockerfile
    restart: on-failure
    env_file: .env-front
    networks:
      - back
    volumes:
      - front-data:/data # Needed ?

  back:
    image: ghcr.io/thetranscendenceteam/back:latest
    build:
      context: ..
      dockerfile: images/back/Dockerfile
    restart: on-failure
    env_file: .env-back
    depends_on:
      - postgres
    platform: linux/amd64
    networks:
      - db
      - back
    volumes:
      - ../src/back/prisma/migrations:/app/prisma/migrations
      - back-data:/data # Needed ?

  adminer:
    image: adminer
    restart: on-failure
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    ports:
      - 8081:8080
    networks:
      - back

  nginx:
    image: ghcr.io/thetranscendenceteam/nginx:latest
    build:
      context: ..
      dockerfile: images/nginx/Dockerfile
    restart: on-failure
    depends_on:
      - back
      - front
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - back
    volumes:
      - nginx-ssl:/etc/nginx/ssl

volumes:
  postgres-data:
  front-data:
  back-data:
  nginx-ssl:

networks:
  back:
  db:
